// AUTO-GENERATED by scripts/build-wiring-library.py — do not hand-edit.
import type { WiringDoc, ConnectorPinout } from '../types';

export const wiringDocs: WiringDoc[] = [
  {
    "id": "audio-system-premium",
    "title": "Audio System \u2014 Premium",
    "category": "Infotainment & Safety",
    "file": "manuals/wiring/AUDIO-SYSTEM---PREMIUM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/audio-system-premium-p1.jpg"
    ]
  },
  {
    "id": "automatic-sway-bar",
    "title": "Automatic Sway Bar",
    "category": "Chassis & Drivetrain",
    "file": "manuals/wiring/AUTOMATIC-SWAY-BAR.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/automatic-sway-bar-p1.jpg"
    ]
  },
  {
    "id": "axle-locker-system",
    "title": "Axle Locker System",
    "category": "Chassis & Drivetrain",
    "file": "manuals/wiring/AXLE-LOCKER-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/axle-locker-system-p1.jpg"
    ]
  },
  {
    "id": "back-up-camera-system",
    "title": "Backup Camera System",
    "category": "Infotainment & Safety",
    "file": "manuals/wiring/BACK-UP-CAMERA-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/back-up-camera-system-p1.jpg"
    ]
  },
  {
    "id": "back-up-lamps-system",
    "title": "Backup Lamps System",
    "category": "Lighting & Horns",
    "file": "manuals/wiring/BACK-UP-LAMPS-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/back-up-lamps-system-p1.jpg"
    ]
  },
  {
    "id": "blind-spot-monitor-system",
    "title": "Blind Spot Monitor System",
    "category": "Infotainment & Safety",
    "file": "manuals/wiring/BLIND-SPOT-MONITOR-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/blind-spot-monitor-system-p1.jpg"
    ]
  },
  {
    "id": "brake-system",
    "title": "Brake System",
    "category": "Chassis & Drivetrain",
    "file": "manuals/wiring/BRAKE-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/brake-system-p1.jpg"
    ]
  },
  {
    "id": "cabin-heater-system",
    "title": "Cabin Heater System",
    "category": "Comfort & Body",
    "file": "manuals/wiring/CABIN-HEATER-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/cabin-heater-system-p1.jpg"
    ]
  },
  {
    "id": "can-c-bus-layout",
    "title": "CAN C Bus Layout",
    "category": "Network & Data",
    "file": "manuals/wiring/CAN-C-BUS-LAYOUT.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/can-c-bus-layout-p1.jpg"
    ]
  },
  {
    "id": "can-c-bus-system",
    "title": "CAN C Bus System",
    "category": "Network & Data",
    "file": "manuals/wiring/CAN-C-BUS-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/can-c-bus-system-p1.jpg"
    ]
  },
  {
    "id": "can-ihs-bus-layout",
    "title": "CAN IHS Bus Layout",
    "category": "Network & Data",
    "file": "manuals/wiring/CAN-IHS-BUS-LAYOUT.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/can-ihs-bus-layout-p1.jpg"
    ]
  },
  {
    "id": "can-ihs-bus-system",
    "title": "CAN IHS Bus System",
    "category": "Network & Data",
    "file": "manuals/wiring/CAN-IHS-BUS-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/can-ihs-bus-system-p1.jpg"
    ]
  },
  {
    "id": "can-private-bus-system",
    "title": "CAN Private Bus System",
    "category": "Network & Data",
    "file": "manuals/wiring/CAN-PRIVATE-BUS-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/can-private-bus-system-p1.jpg"
    ]
  },
  {
    "id": "data-link-connector",
    "title": "Data Link Connector",
    "category": "Network & Data",
    "file": "manuals/wiring/DATA-LINK-CONNECTOR.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/data-link-connector-p1.jpg"
    ]
  },
  {
    "id": "defogger-system",
    "title": "Defogger System",
    "category": "Lighting & Horns",
    "file": "manuals/wiring/DEFOGGER-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/defogger-system-p1.jpg"
    ]
  },
  {
    "id": "digital-tv-system",
    "title": "Digital TV System",
    "category": "Infotainment & Safety",
    "file": "manuals/wiring/DIGITAL-TV-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/digital-tv-system-p1.jpg"
    ]
  },
  {
    "id": "electro-hydraulic-power-steering-ehps-system-ess",
    "title": "Electro Hydraulic Power Steering (EHPS) System \u2014 ESS",
    "category": "Chassis & Drivetrain",
    "file": "manuals/wiring/ELECTRO-HYDRAULIC-POWER-STEERING-(EHPS)-SYSTEM---ESS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/electro-hydraulic-power-steering-ehps-system-ess-p1.jpg"
    ]
  },
  {
    "id": "emergency-response-assistance-system",
    "title": "Emergency Response Assistance System",
    "category": "Infotainment & Safety",
    "file": "manuals/wiring/EMERGENCY-RESPONSE-ASSISTANCE-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/emergency-response-assistance-system-p1.jpg"
    ]
  },
  {
    "id": "entire-vehicle-connector-map",
    "title": "Entire Vehicle Connector Map",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/ENTIRE-VEHICLE-CONNECTOR-MAP.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/entire-vehicle-connector-map-p1.jpg"
    ]
  },
  {
    "id": "fog-lamps-system",
    "title": "Fog Lamps System",
    "category": "Lighting & Horns",
    "file": "manuals/wiring/FOG-LAMPS-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fog-lamps-system-p1.jpg"
    ]
  },
  {
    "id": "front-fog-light-connector-inline-details",
    "title": "Front Fog Light Connector Inline Details",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/FRONT-FOG-LIGHT-connector-inline-details.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/front-fog-light-connector-inline-details-p1.jpg"
    ],
    "pinout": true
  },
  {
    "id": "fuses-battery-ess",
    "title": "Fuses \u2014 Battery \u2014 ESS",
    "category": "Power Distribution",
    "file": "manuals/wiring/FUSES---BATTERY---ESS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fuses-battery-ess-p1.jpg"
    ]
  },
  {
    "id": "fuses-battery-etorque",
    "title": "Fuses \u2014 Battery \u2014 eTorque",
    "category": "Power Distribution",
    "file": "manuals/wiring/FUSES---BATTERY---eTORQUE.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fuses-battery-etorque-p1.jpg"
    ]
  },
  {
    "id": "fuses-relay-asd-2-0l",
    "title": "Fuses Relay \u2014 ASD \u2014 2.0L",
    "category": "Power Distribution",
    "file": "manuals/wiring/FUSES_RELAY---ASD---2.0L.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fuses-relay-asd-2-0l-p1.jpg"
    ]
  },
  {
    "id": "fuses-relay-asd-3-6l",
    "title": "Fuses Relay \u2014 ASD \u2014 3.6L",
    "category": "Power Distribution",
    "file": "manuals/wiring/FUSES_RELAY---ASD---3.6L.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fuses-relay-asd-3-6l-p1.jpg"
    ]
  },
  {
    "id": "fuses-relay-asd-diesel-2-2l",
    "title": "Fuses Relay \u2014 ASD \u2014 Diesel \u2014 2.2L",
    "category": "Power Distribution",
    "file": "manuals/wiring/FUSES_RELAY---ASD---DIESEL---2.2L.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fuses-relay-asd-diesel-2-2l-p1.jpg"
    ]
  },
  {
    "id": "fuses-relay-miscellaneous-2-0l-3-6l-ess",
    "title": "Fuses Relay \u2014 Miscellaneous \u2014 2.0L 3.6L \u2014 ESS",
    "category": "Power Distribution",
    "file": "manuals/wiring/FUSES_RELAY---MISCELLANEOUS---2.0L_3.6L---ESS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fuses-relay-miscellaneous-2-0l-3-6l-ess-p1.jpg"
    ]
  },
  {
    "id": "fuses-relay-miscellaneous-diesel",
    "title": "Fuses Relay \u2014 Miscellaneous \u2014 Diesel",
    "category": "Power Distribution",
    "file": "manuals/wiring/FUSES_RELAY---MISCELLANEOUS---DIESEL.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fuses-relay-miscellaneous-diesel-p1.jpg"
    ]
  },
  {
    "id": "fuses-relay-miscellaneous",
    "title": "Fuses Relay \u2014 Miscellaneous",
    "category": "Power Distribution",
    "file": "manuals/wiring/FUSES_RELAY---MISCELLANEOUS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fuses-relay-miscellaneous-p1.jpg"
    ]
  },
  {
    "id": "fuses-relay-run-acc",
    "title": "Fuses Relay \u2014 Run ACC",
    "category": "Power Distribution",
    "file": "manuals/wiring/FUSES_RELAY---RUN_ACC.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fuses-relay-run-acc-p1.jpg"
    ]
  },
  {
    "id": "fuses-relay-run-start",
    "title": "Fuses Relay \u2014 Run Start",
    "category": "Power Distribution",
    "file": "manuals/wiring/FUSES_RELAY---RUN_START.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/fuses-relay-run-start-p1.jpg"
    ]
  },
  {
    "id": "hands-free-system",
    "title": "Hands Free System",
    "category": "Infotainment & Safety",
    "file": "manuals/wiring/HANDS-FREE-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/hands-free-system-p1.jpg"
    ]
  },
  {
    "id": "headlamps-system",
    "title": "Headlamps System",
    "category": "Lighting & Horns",
    "file": "manuals/wiring/HEADLAMPS-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/headlamps-system-p1.jpg"
    ]
  },
  {
    "id": "heated-seat-system",
    "title": "Heated Seat System",
    "category": "Comfort & Body",
    "file": "manuals/wiring/HEATED-SEAT-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/heated-seat-system-p1.jpg"
    ]
  },
  {
    "id": "heated-steering-wheel-system",
    "title": "Heated Steering Wheel System",
    "category": "Comfort & Body",
    "file": "manuals/wiring/HEATED-STEERING-WHEEL-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/heated-steering-wheel-system-p1.jpg"
    ]
  },
  {
    "id": "horns",
    "title": "Horns",
    "category": "Lighting & Horns",
    "file": "manuals/wiring/HORNS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/horns-p1.jpg"
    ]
  },
  {
    "id": "hvac-system-atc",
    "title": "HVAC System \u2014 ATC",
    "category": "Comfort & Body",
    "file": "manuals/wiring/HVAC-SYSTEM---ATC.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/hvac-system-atc-p1.jpg"
    ]
  },
  {
    "id": "interior-lighting-system",
    "title": "Interior Lighting System",
    "category": "Lighting & Horns",
    "file": "manuals/wiring/INTERIOR-LIGHTING-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/interior-lighting-system-p1.jpg"
    ]
  },
  {
    "id": "lamp-assembly-left-front-c1-connector-details",
    "title": "Lamp Assembly Left Front C1 Connector Details",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/LAMP-ASSEMBLY-LEFT-FRONT-C1-connector-details.pdf",
    "pages": 2,
    "thumbs": [
      "figures/wiring/lamp-assembly-left-front-c1-connector-details-p1.jpg",
      "figures/wiring/lamp-assembly-left-front-c1-connector-details-p2.jpg"
    ],
    "pinout": true
  },
  {
    "id": "lamp-assembly-right-front-c1-connector-details",
    "title": "Lamp Assembly Right Front C1 Connector Details",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/LAMP-ASSEMBLY-RIGHT-FRONT-C1-connector-details.pdf",
    "pages": 2,
    "thumbs": [
      "figures/wiring/lamp-assembly-right-front-c1-connector-details-p1.jpg",
      "figures/wiring/lamp-assembly-right-front-c1-connector-details-p2.jpg"
    ],
    "pinout": true
  },
  {
    "id": "lamp-assembly-right-front-c2-connector-details",
    "title": "Lamp Assembly Right Front C2 Connector Details",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/LAMP-ASSEMBLY-RIGHT-FRONT-C2-connector-details.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/lamp-assembly-right-front-c2-connector-details-p1.jpg"
    ],
    "pinout": true
  },
  {
    "id": "lamp-assembly-tail-right-connector-details",
    "title": "Lamp Assembly Tail Right Connector Details",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/LAMP-ASSEMBLY-TAIL-RIGHT-connector-details.pdf",
    "pages": 2,
    "thumbs": [
      "figures/wiring/lamp-assembly-tail-right-connector-details-p1.jpg",
      "figures/wiring/lamp-assembly-tail-right-connector-details-p2.jpg"
    ],
    "pinout": true
  },
  {
    "id": "lamp-drl-left-base-connector-details",
    "title": "Lamp DRL Left Base Connector Details",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/LAMP-DRL-LEFT-BASE-connector-details.pdf",
    "pages": 2,
    "thumbs": [
      "figures/wiring/lamp-drl-left-base-connector-details-p1.jpg",
      "figures/wiring/lamp-drl-left-base-connector-details-p2.jpg"
    ],
    "pinout": true
  },
  {
    "id": "lamp-drl-right-base-connector-details",
    "title": "Lamp DRL Right Base Connector Details",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/LAMP-DRL-RIGHT-BASE-connector-details.pdf",
    "pages": 2,
    "thumbs": [
      "figures/wiring/lamp-drl-right-base-connector-details-p1.jpg",
      "figures/wiring/lamp-drl-right-base-connector-details-p2.jpg"
    ],
    "pinout": true
  },
  {
    "id": "lamp-drl-right-premium-connector-details",
    "title": "Lamp DRL Right Premium Connector Details",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/LAMP-DRL-RIGHT-PREMIUM-connector-details.pdf",
    "pages": 2,
    "thumbs": [
      "figures/wiring/lamp-drl-right-premium-connector-details-p1.jpg",
      "figures/wiring/lamp-drl-right-premium-connector-details-p2.jpg"
    ],
    "pinout": true
  },
  {
    "id": "lin-bus-system",
    "title": "LIN Bus System",
    "category": "Network & Data",
    "file": "manuals/wiring/LIN-BUS-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/lin-bus-system-p1.jpg"
    ]
  },
  {
    "id": "lock-system-base",
    "title": "Lock System \u2014 Base",
    "category": "Locks & Security",
    "file": "manuals/wiring/LOCK-SYSTEM---BASE.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/lock-system-base-p1.jpg"
    ]
  },
  {
    "id": "lock-system-premium",
    "title": "Lock System \u2014 Premium",
    "category": "Locks & Security",
    "file": "manuals/wiring/LOCK-SYSTEM---PREMIUM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/lock-system-premium-p1.jpg"
    ]
  },
  {
    "id": "media-port-base",
    "title": "Media Port \u2014 Base",
    "category": "Infotainment & Safety",
    "file": "manuals/wiring/MEDIA-PORT---BASE.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/media-port-base-p1.jpg"
    ]
  },
  {
    "id": "message-systems",
    "title": "Message Systems",
    "category": "Network & Data",
    "file": "manuals/wiring/MESSAGE-SYSTEMS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/message-systems-p1.jpg"
    ]
  },
  {
    "id": "mirror-interior",
    "title": "Mirror \u2014 Interior",
    "category": "Comfort & Body",
    "file": "manuals/wiring/MIRROR---INTERIOR.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/mirror-interior-p1.jpg"
    ]
  },
  {
    "id": "module-body-control-layout",
    "title": "Module \u2014 Body Control Layout",
    "category": "Power Distribution",
    "file": "manuals/wiring/MODULE---BODY-CONTROL-LAYOUT.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/module-body-control-layout-p1.jpg"
    ]
  },
  {
    "id": "power-distribution-center-layout",
    "title": "Power Distribution Center Layout",
    "category": "Power Distribution",
    "file": "manuals/wiring/POWER-DISTRIBUTION-CENTER-LAYOUT.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/power-distribution-center-layout-p1.jpg"
    ]
  },
  {
    "id": "power-outlets",
    "title": "Power Outlets",
    "category": "Comfort & Body",
    "file": "manuals/wiring/POWER-OUTLETS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/power-outlets-p1.jpg"
    ]
  },
  {
    "id": "power-top-system",
    "title": "Power Top System",
    "category": "Comfort & Body",
    "file": "manuals/wiring/POWER-TOP-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/power-top-system-p1.jpg"
    ]
  },
  {
    "id": "rear-fog-light-connector-inline-details",
    "title": "Rear Fog Light Connector Inline Details",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/REAR-FOG-LIGHT-connector-inline-details.pdf",
    "pages": 2,
    "thumbs": [
      "figures/wiring/rear-fog-light-connector-inline-details-p1.jpg",
      "figures/wiring/rear-fog-light-connector-inline-details-p2.jpg"
    ],
    "pinout": true
  },
  {
    "id": "remote-start-system",
    "title": "Remote Start System",
    "category": "Locks & Security",
    "file": "manuals/wiring/REMOTE-START-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/remote-start-system-p1.jpg"
    ]
  },
  {
    "id": "restraint-systems",
    "title": "Restraint Systems",
    "category": "Infotainment & Safety",
    "file": "manuals/wiring/RESTRAINT-SYSTEMS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/restraint-systems-p1.jpg"
    ]
  },
  {
    "id": "starting-charging-system-2-0l-etorque",
    "title": "Starting & Charging System \u2014 2.0L \u2014 eTorque",
    "category": "Starting & Charging",
    "file": "manuals/wiring/STARTING_CHARGING-SYSTEM---2.0L---eTORQUE.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/starting-charging-system-2-0l-etorque-p1.jpg"
    ]
  },
  {
    "id": "starting-charging-system-2-2l-ess",
    "title": "Starting & Charging System \u2014 2.2L \u2014 ESS",
    "category": "Starting & Charging",
    "file": "manuals/wiring/STARTING_CHARGING-SYSTEM---2.2L---ESS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/starting-charging-system-2-2l-ess-p1.jpg"
    ]
  },
  {
    "id": "stop-lamps-system",
    "title": "Stop Lamps System",
    "category": "Lighting & Horns",
    "file": "manuals/wiring/STOP-LAMPS-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/stop-lamps-system-p1.jpg"
    ]
  },
  {
    "id": "swinggate-lock-system",
    "title": "Swinggate \u2014 Lock System",
    "category": "Locks & Security",
    "file": "manuals/wiring/SWINGGATE---LOCK-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/swinggate-lock-system-p1.jpg"
    ]
  },
  {
    "id": "tire-pressure-monitoring-tpm-system",
    "title": "Tire Pressure Monitoring (TPM) System",
    "category": "Chassis & Drivetrain",
    "file": "manuals/wiring/TIRE-PRESSURE-MONITORING-(TPM)-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/tire-pressure-monitoring-tpm-system-p1.jpg"
    ]
  },
  {
    "id": "trailer-tow-system",
    "title": "Trailer Tow System",
    "category": "Chassis & Drivetrain",
    "file": "manuals/wiring/TRAILER-TOW-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/trailer-tow-system-p1.jpg"
    ]
  },
  {
    "id": "transfer-case",
    "title": "Transfer Case",
    "category": "Chassis & Drivetrain",
    "file": "manuals/wiring/TRANSFER-CASE.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/transfer-case-p1.jpg"
    ]
  },
  {
    "id": "transmission-850re-2-0l-2-2l-3-6l",
    "title": "Transmission \u2014 850RE \u2014 2.0L 2.2L 3.6L",
    "category": "Chassis & Drivetrain",
    "file": "manuals/wiring/TRANSMISSION---850RE---2.0L_2.2L_3.6L.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/transmission-850re-2-0l-2-2l-3-6l-p1.jpg"
    ]
  },
  {
    "id": "transmission-manual-3-6l",
    "title": "Transmission \u2014 Manual \u2014 3.6L",
    "category": "Chassis & Drivetrain",
    "file": "manuals/wiring/TRANSMISSION---MANUAL---3.6L.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/transmission-manual-3-6l-p1.jpg"
    ]
  },
  {
    "id": "turn-signal-lamps-system",
    "title": "Turn Signal Lamps System",
    "category": "Lighting & Horns",
    "file": "manuals/wiring/TURN-SIGNAL-LAMPS-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/turn-signal-lamps-system-p1.jpg"
    ]
  },
  {
    "id": "universal-transmitter",
    "title": "Universal Transmitter",
    "category": "Locks & Security",
    "file": "manuals/wiring/UNIVERSAL-TRANSMITTER.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/universal-transmitter-p1.jpg"
    ]
  },
  {
    "id": "upfitters",
    "title": "Upfitters",
    "category": "Comfort & Body",
    "file": "manuals/wiring/UPFITTERS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/upfitters-p1.jpg"
    ]
  },
  {
    "id": "vehicle-ground-inline-connector-map",
    "title": "Vehicle Ground Inline Connector Map",
    "category": "Connectors & Grounds",
    "file": "manuals/wiring/VEHICLE-GROUND_INLINE-CONNECTOR-MAP.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/vehicle-ground-inline-connector-map-p1.jpg"
    ]
  },
  {
    "id": "vehicle-theft-security-system",
    "title": "Vehicle Theft Security System",
    "category": "Locks & Security",
    "file": "manuals/wiring/VEHICLE-THEFT-SECURITY-SYSTEM.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/vehicle-theft-security-system-p1.jpg"
    ]
  },
  {
    "id": "windows",
    "title": "Windows",
    "category": "Comfort & Body",
    "file": "manuals/wiring/WINDOWS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/windows-p1.jpg"
    ]
  },
  {
    "id": "wiper-washer-systems",
    "title": "Wiper Washer Systems",
    "category": "Comfort & Body",
    "file": "manuals/wiring/WIPER_WASHER-SYSTEMS.pdf",
    "pages": 1,
    "thumbs": [
      "figures/wiring/wiper-washer-systems-p1.jpg"
    ]
  }
];

export const connectorPinouts: ConnectorPinout[] = [
  {
    "id": "front-fog-light-connector-inline-details",
    "meta": {
      "Connector No": "XY101A",
      "Option": "Connector Details",
      "name": "7283-5570-10"
    },
    "pins": [
      {
        "pin": "1",
        "circuit": "L90",
        "color": "WH/OG",
        "gauge": "0.75",
        "function": "RIGHT FRONT FOG LAMP CONTROL",
        "option": ""
      },
      {
        "pin": "2",
        "circuit": "L89",
        "color": "WH/YE",
        "gauge": "0.75",
        "function": "LEFT FRONT FOG LAMP CONTROL",
        "option": ""
      },
      {
        "pin": "3",
        "circuit": "Z906",
        "color": "BK",
        "gauge": "1.0",
        "function": "GROUND",
        "option": ""
      },
      {
        "pin": "4",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": "XY101A"
      }
    ]
  },
  {
    "id": "lamp-assembly-left-front-c1-connector-details",
    "meta": {
      "Harness Family": "Dash",
      "Color": "BLACK",
      "Gender": "FEMALE",
      "Part Number": "33472-0601",
      "Part Description": "Connector No:",
      "Connector No": "D6605A",
      "Option": "Standard",
      "Repair Kit Part Number": "68225123AA",
      "Cavity Count": "6",
      "name": "LAMP-ASSEMBLY-LEFT FRONT C1"
    },
    "pins": [
      {
        "pin": "1",
        "circuit": "Z905",
        "color": "BK",
        "gauge": "1.5",
        "function": "GROUND",
        "option": ""
      },
      {
        "pin": "2",
        "circuit": "L43",
        "color": "WH/DB",
        "gauge": "1.5",
        "function": "LEFT LOW BEAM DRIVER",
        "option": ""
      },
      {
        "pin": "3",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": ""
      },
      {
        "pin": "4",
        "circuit": "L33",
        "color": "WH/GN",
        "gauge": "2.0",
        "function": "LEFT HIGH BEAM DRIVER 11/30/2018",
        "option": ""
      },
      {
        "pin": "5",
        "circuit": "L117",
        "color": "BG/DB",
        "gauge": "0.50",
        "function": "LEFT FRONT PARK LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "6",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT 11/30/2018",
        "option": ""
      }
    ]
  },
  {
    "id": "lamp-assembly-right-front-c1-connector-details",
    "meta": {
      "Harness Family": "Dash",
      "Color": "BLACK",
      "Gender": "FEMALE",
      "Part Number": "33472-0601",
      "Part Description": "Connector No:",
      "Connector No": "D6606A",
      "Option": "Standard",
      "Repair Kit Part Number": "68225123AA",
      "Cavity Count": "6",
      "name": "LAMP-ASSEMBLY-RIGHT FRONT C1"
    },
    "pins": [
      {
        "pin": "1",
        "circuit": "Z904",
        "color": "BK",
        "gauge": "1.5",
        "function": "GROUND",
        "option": ""
      },
      {
        "pin": "2",
        "circuit": "L44",
        "color": "WH/BG",
        "gauge": "1.5",
        "function": "RIGHT LOW BEAM DRIVER",
        "option": ""
      },
      {
        "pin": "3",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": ""
      },
      {
        "pin": "4",
        "circuit": "L34",
        "color": "WH/GY",
        "gauge": "2.0",
        "function": "RIGHT HIGH BEAM DRIVER 11/30/2018",
        "option": ""
      },
      {
        "pin": "5",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": "EXCEPT EXPORT BASE"
      },
      {
        "pin": "5",
        "circuit": "L118",
        "color": "BG/OG",
        "gauge": "0.50",
        "function": "RIGHT FRONT PARK LAMP DRIVER",
        "option": "EXCEPT EXPORT PREMIUM"
      },
      {
        "pin": "5",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": "EXPORT"
      },
      {
        "pin": "6",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT 11/30/2018",
        "option": ""
      }
    ]
  },
  {
    "id": "lamp-assembly-right-front-c2-connector-details",
    "meta": {
      "Harness Family": "Dash",
      "Color": "BLACK",
      "Gender": "FEMALE",
      "Part Number": "7283-8852-30",
      "Part Description": "Connector No:",
      "Connector No": "D6606B",
      "Option": "Standard",
      "Repair Kit Part Number": "Not Available",
      "Cavity Count": "3",
      "name": "LAMP-ASSEMBLY-RIGHT FRONT C2"
    },
    "pins": [
      {
        "pin": "1",
        "circuit": "F927",
        "color": "PK/YE",
        "gauge": "0.50",
        "function": "FUSED IGNITION",
        "option": ""
      },
      {
        "pin": "2",
        "circuit": "L133",
        "color": "WH/YE",
        "gauge": "0.35",
        "function": "HEADLAMP LEVEL MOTOR SIGNAL",
        "option": "BASE"
      },
      {
        "pin": "2",
        "circuit": "L132",
        "color": "GN/WH",
        "gauge": "0.35",
        "function": "RIGHT HEADLAMP LEVEL SENSOR SIGNAL",
        "option": "PREMIUM"
      },
      {
        "pin": "3",
        "circuit": "Z904",
        "color": "BK",
        "gauge": "0.35",
        "function": "GROUND 11/30/2018",
        "option": ""
      }
    ]
  },
  {
    "id": "lamp-assembly-tail-right-connector-details",
    "meta": {
      "Harness Family": "Body",
      "Color": "BLACK",
      "Gender": "MALE",
      "Part Number": "33482-1201",
      "Part Description": "STANDARD CONNECTOR BLADE 2ROW HOUSING",
      "Connector No": "D6642A",
      "Option": "Standard",
      "Repair Kit Part Number": "68364268AA",
      "Cavity Count": "12",
      "name": "LAMP-ASSEMBLY TAIL-RIGHT"
    },
    "pins": [
      {
        "pin": "1",
        "circuit": "L54",
        "color": "WH/GN",
        "gauge": "0.75",
        "function": "RIGHT STOP LAMP DRIVER",
        "option": "PREMIUM LIGHTING EXPORT"
      },
      {
        "pin": "1",
        "circuit": "L6",
        "color": "GN",
        "gauge": "0.75",
        "function": "RIGHT STOP/TURN FEED",
        "option": "BASE LIGHTING EXCEPT EXPORT"
      },
      {
        "pin": "1",
        "circuit": "L54",
        "color": "WH/GN",
        "gauge": "0.75",
        "function": "RIGHT STOP LAMP DRIVER",
        "option": "BASE LIGHTING EXPORT"
      },
      {
        "pin": "1",
        "circuit": "L6",
        "color": "GN",
        "gauge": "0.75",
        "function": "RIGHT STOP/TURN FEED",
        "option": "PREMIUM LIGHTING EXCEPT EXPORT"
      },
      {
        "pin": "2",
        "circuit": "L144",
        "color": "BG/OG",
        "gauge": "0.75",
        "function": "RIGHT SIDE MARKER CONTROL",
        "option": ""
      },
      {
        "pin": "3",
        "circuit": "L62",
        "color": "WH/YE",
        "gauge": "0.75",
        "function": "RIGHT REAR TURN LAMP DRIVER",
        "option": "BASE LIGHTING EXPORT"
      },
      {
        "pin": "3",
        "circuit": "L62",
        "color": "WH/YE",
        "gauge": "0.75",
        "function": "RIGHT REAR TURN LAMP DRIVER",
        "option": "PREMIUM LIGHTING EXPORT"
      },
      {
        "pin": "4",
        "circuit": "L72",
        "color": "WH/OG",
        "gauge": "0.75",
        "function": "RIGHT REAR PARK LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "5",
        "circuit": "L16",
        "color": "WH/VT",
        "gauge": "0.75",
        "function": "RIGHT BACKUP LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "6",
        "circuit": "Z916",
        "color": "BK",
        "gauge": "0.75",
        "function": "GROUND",
        "option": ""
      },
      {
        "pin": "7",
        "circuit": "Z916",
        "color": "BK",
        "gauge": "0.75",
        "function": "GROUND",
        "option": ""
      },
      {
        "pin": "8",
        "circuit": "L562",
        "color": "WH/BG",
        "gauge": "0.35",
        "function": "RIGHT REAR LIGHTING FAULT SENSE",
        "option": "PREMIUM LIGHTING EXCEPT EXPORT"
      },
      {
        "pin": "8",
        "circuit": "L562",
        "color": "WH/BG",
        "gauge": "0.35",
        "function": "RIGHT REAR LIGHTING FAULT SENSE",
        "option": "PREMIUM LIGHTING EXPORT"
      },
      {
        "pin": "9",
        "circuit": "F923",
        "color": "PK/YE",
        "gauge": "0.35",
        "function": "RUN RELAY CONTROL",
        "option": "PREMIUM LIGHTING EXCEPT EXPORT"
      },
      {
        "pin": "9",
        "circuit": "F923",
        "color": "PK/YE",
        "gauge": "0.35",
        "function": "RUN RELAY CONTROL",
        "option": "PREMIUM LIGHTING EXPORT"
      },
      {
        "pin": "10",
        "circuit": "D217",
        "color": "DG/WH",
        "gauge": "0.35",
        "function": "CAN IHS (+)",
        "option": "PREMIUM LIGHTING EXPORT"
      },
      {
        "pin": "10",
        "circuit": "D217",
        "color": "DG/WH",
        "gauge": "0.35",
        "function": "CAN IHS (+)",
        "option": "PREMIUM LIGHTING EXCEPT EXPORT"
      },
      {
        "pin": "11",
        "circuit": "D218",
        "color": "WH",
        "gauge": "0.35",
        "function": "CAN IHS (-)",
        "option": "PREMIUM LIGHTING EXCEPT EXPORT"
      },
      {
        "pin": "11",
        "circuit": "D218",
        "color": "WH",
        "gauge": "0.35",
        "function": "CAN IHS (-)",
        "option": "PREMIUM LIGHTING EXPORT"
      },
      {
        "pin": "12",
        "circuit": "P712",
        "color": "GN/WH",
        "gauge": "0.35",
        "function": "RIGHT BLIND SPOT INDICATOR DRIVER",
        "option": "PREMIUM LIGHTING EXCEPT EXPORT"
      },
      {
        "pin": "12",
        "circuit": "P712",
        "color": "GN/WH",
        "gauge": "0.35",
        "function": "RIGHT BLIND SPOT INDICATOR DRIVER",
        "option": "PREMIUM LIGHTING EXPORT 11/30/2018"
      }
    ]
  },
  {
    "id": "lamp-drl-left-base-connector-details",
    "meta": {
      "Harness Family": "Dash",
      "Color": "BLACK",
      "Gender": "MALE",
      "Part Number": "34899-6120",
      "Part Description": "Connector No:",
      "Connector No": "D2690A",
      "Option": "BASE",
      "Repair Kit Part Number": "Cavity Count:",
      "Cavity Count": "6",
      "name": "LAMP-DRL LEFT"
    },
    "pins": [
      {
        "pin": "1",
        "circuit": "L145",
        "color": "WH/OG",
        "gauge": "0.75",
        "function": "LEFT SIDE MARKER CONTROL",
        "option": "BASE"
      },
      {
        "pin": "2",
        "circuit": "L61",
        "color": "WH/GN",
        "gauge": "0.75",
        "function": "LEFT FRONT TURN LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "3",
        "circuit": "Z905",
        "color": "BK",
        "gauge": "0.75",
        "function": "GROUND",
        "option": ""
      },
      {
        "pin": "4",
        "circuit": "L77",
        "color": "WH/BN",
        "gauge": "0.75",
        "function": "LEFT FRONT PARK LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "5",
        "circuit": "L58",
        "color": "WH/YE",
        "gauge": "0.75",
        "function": "LEFT DRL LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "6",
        "circuit": "Z905",
        "color": "BK",
        "gauge": "0.75",
        "function": "GROUND 11/30/2018",
        "option": ""
      }
    ]
  },
  {
    "id": "lamp-drl-right-base-connector-details",
    "meta": {
      "Harness Family": "Dash",
      "Color": "BLACK",
      "Gender": "MALE",
      "Part Number": "34899-6120",
      "Part Description": "Connector No:",
      "Connector No": "D2691A",
      "Option": "BASE",
      "Repair Kit Part Number": "Cavity Count:",
      "Cavity Count": "6",
      "name": "LAMP-DRL RIGHT"
    },
    "pins": [
      {
        "pin": "1",
        "circuit": "L144",
        "color": "BG/OG",
        "gauge": "0.75",
        "function": "RIGHT SIDE MARKER CONTROL",
        "option": "BASE"
      },
      {
        "pin": "2",
        "circuit": "L60",
        "color": "WH/BG",
        "gauge": "0.75",
        "function": "RIGHT FRONT TURN LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "3",
        "circuit": "Z904",
        "color": "BK",
        "gauge": "0.75",
        "function": "GROUND",
        "option": ""
      },
      {
        "pin": "4",
        "circuit": "L78",
        "color": "WH/OG",
        "gauge": "0.75",
        "function": "RIGHT FRONT PARK LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "5",
        "circuit": "L59",
        "color": "WH/DB",
        "gauge": "0.75",
        "function": "RIGHT DRL LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "6",
        "circuit": "Z904",
        "color": "BK",
        "gauge": "0.75",
        "function": "GROUND 11/30/2018",
        "option": ""
      }
    ]
  },
  {
    "id": "lamp-drl-right-premium-connector-details",
    "meta": {
      "Harness Family": "Dash",
      "Color": "BLACK",
      "Gender": "MALE",
      "Part Number": "34899-6120",
      "Part Description": "Connector No:",
      "Connector No": "D2691A",
      "Option": "PREMIUM",
      "Repair Kit Part Number": "Cavity Count:",
      "Cavity Count": "6",
      "name": "LAMP-DRL RIGHT"
    },
    "pins": [
      {
        "pin": "1",
        "circuit": "L552",
        "color": "BG/OG",
        "gauge": "0.35",
        "function": "RIGHT FRONT LIGHTING FAULT SENSE",
        "option": "PREMIUM"
      },
      {
        "pin": "2",
        "circuit": "L60",
        "color": "WH/BG",
        "gauge": "0.75",
        "function": "RIGHT FRONT TURN LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "3",
        "circuit": "Z904",
        "color": "BK",
        "gauge": "0.75",
        "function": "GROUND",
        "option": ""
      },
      {
        "pin": "4",
        "circuit": "L78",
        "color": "WH/OG",
        "gauge": "0.75",
        "function": "RIGHT FRONT PARK LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "5",
        "circuit": "L59",
        "color": "WH/DB",
        "gauge": "0.75",
        "function": "RIGHT DRL LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "6",
        "circuit": "Z904",
        "color": "BK",
        "gauge": "0.75",
        "function": "GROUND 11/30/2018",
        "option": ""
      }
    ]
  },
  {
    "id": "rear-fog-light-connector-inline-details",
    "meta": {
      "Connector No": "XY500A",
      "Option": "Connector Details",
      "name": "807-479-501"
    },
    "pins": [
      {
        "pin": "1",
        "circuit": "D704",
        "color": "WH/DG",
        "gauge": "0.35",
        "function": "PARK ASSIST SIGNAL 10",
        "option": ""
      },
      {
        "pin": "2",
        "circuit": "D701",
        "color": "WH/BU",
        "gauge": "0.35",
        "function": "PARK ASSIST SIGNAL 8",
        "option": ""
      },
      {
        "pin": "3",
        "circuit": "D703",
        "color": "WH/OG",
        "gauge": "0.35",
        "function": "PARK ASSIST SIGNAL 9",
        "option": ""
      },
      {
        "pin": "4",
        "circuit": "L3",
        "color": "WH/DB",
        "gauge": "0.50",
        "function": "LICENSE PLATE LAMP DRIVER",
        "option": ""
      },
      {
        "pin": "5",
        "circuit": "D710",
        "color": "WH",
        "gauge": "0.35",
        "function": "PARK ASSIST SIGNAL 11",
        "option": ""
      },
      {
        "pin": "6",
        "circuit": "L898",
        "color": "WH/DG",
        "gauge": "0.50",
        "function": "FOG RR LAMP FEED 2",
        "option": ""
      },
      {
        "pin": "7",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": "XY500A"
      },
      {
        "pin": "8",
        "circuit": "Z915",
        "color": "BK",
        "gauge": "0.50",
        "function": "GROUND",
        "option": "REAR BUMPER Z915 GROUND BK 0.50 LATE BUILD REAR BUMPER Z919 GROUND BK 0.35 EARLY BUILD"
      },
      {
        "pin": "9",
        "circuit": "X700",
        "color": "GY/OG",
        "gauge": "0.35",
        "function": "REAR PARK ASSIST SENSOR SUPPLY",
        "option": ""
      },
      {
        "pin": "10",
        "circuit": "X750",
        "color": "GY/BU",
        "gauge": "0.35",
        "function": "REAR PARK ASSIST SENSOR GROUND",
        "option": ""
      },
      {
        "pin": "11",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": ""
      },
      {
        "pin": "12",
        "circuit": "L899",
        "color": "WH/OG",
        "gauge": "0.50",
        "function": "REAR FOG LAMP FEED",
        "option": ""
      },
      {
        "pin": "13",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": ""
      },
      {
        "pin": "14",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": ""
      },
      {
        "pin": "15",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": ""
      },
      {
        "pin": "16",
        "circuit": "N0",
        "color": "NA",
        "gauge": "0",
        "function": "NO CONNECT",
        "option": ""
      }
    ]
  }
];
